{"impact": {"pr": null, "a": "COMPLETE", "ac": "LOW", "impact_score": null, "i": "COMPLETE", "cvss3_score": null, "c": "COMPLETE", "vector_string": "AV:N/AC:M/Au:N/C:P/I:P/A:N", "cvss2_severity": "MEDIUM", "cvss3_severity": null, "s": null, "ui": null, "av": "LOCAL", "cvss2_score": 5.8, "au": "SINGLE", "exploitability_score": null}, "license": "Apache-2.0", "name": "python_glanceclient", "cve_id": "CVE-2013-4111", "repository_summary": "OpenStack Image API Client Library", "ochrona_severity_score": 5.8, "repo_url": "https://opendev.org/openstack/python-glanceclient", "latest_version": "2.17.0", "cwe_id": "CWE-20", "language": "python", "publish_date": "2013-08-28T21:55Z", "references": ["http://lists.opensuse.org/opensuse-updates/2013-08/msg00019.html", "http://rhn.redhat.com/errata/RHSA-2013-1200.html", "http://secunia.com/advisories/54313", "http://secunia.com/advisories/54525", "http://www.ubuntu.com/usn/USN-2004-1", "https://bugs.launchpad.net/ossa/+bug/1192229", "https://github.com/openstack/python-glanceclient/blob/master/doc/source/index.rst"], "owner": "openstack", "affected_versions": [{"operator": "<=", "version_value": "0.12.0"}], "description": "The Python client library for Glance (python-glanceclient) before 0.10.0 does not properly check the preverify_ok value, which prevents the server hostname from being verified with a domain name in the subject's Common Name (CN) or subjectAltName field of the X.509 certificate and allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate."}