{"impact": {"pr": null, "a": "COMPLETE", "ac": "LOW", "impact_score": null, "i": "COMPLETE", "cvss3_score": null, "c": "COMPLETE", "vector_string": "AV:N/AC:M/Au:N/C:P/I:P/A:P", "cvss2_severity": "MEDIUM", "cvss3_severity": null, "s": null, "ui": null, "av": "LOCAL", "cvss2_score": 6.8, "au": "SINGLE", "exploitability_score": null}, "license": "LGPL-2.1-or-later", "name": "python-cjson", "cve_id": "CVE-2010-1666", "repository_summary": "A very fast JSON encoder/decoder for Python", "ochrona_severity_score": 6.8, "repo_url": "https://github.com/AGProjects/python-cjson", "latest_version": "1.2.1", "cwe_id": "CWE-119", "language": "python", "publish_date": "2010-07-02T19:00Z", "references": ["http://secunia.com/advisories/40335", "http://secunia.com/advisories/40500", "http://www.debian.org/security/2010/dsa-2068", "http://www.vupen.com/english/advisories/2010/1774", "https://bugs.launchpad.net/ubuntu/+source/python-cjson/+bug/585274"], "owner": "dan_pascu", "affected_versions": [{"operator": "=", "version_value": "1.0.5"}], "description": "Buffer overflow in Dan Pascu python-cjson 1.0.5, when UCS-4 encoding is enabled, allows context-dependent attackers to cause a denial of service (application crash) or possibly have unspecified other impact via vectors involving crafted Unicode input to the cjson.encode function."}