{"impact": {"pr": null, "a": "COMPLETE", "ac": "LOW", "impact_score": null, "i": "COMPLETE", "cvss3_score": null, "c": "COMPLETE", "vector_string": "AV:L/AC:M/Au:N/C:N/I:P/A:P", "cvss2_severity": "LOW", "cvss3_severity": null, "s": null, "ui": null, "av": "LOCAL", "cvss2_score": 3.3, "au": "SINGLE", "exploitability_score": null}, "license": "LGPL-2.0-only", "name": "pyxdg", "cve_id": "CVE-2014-1624", "repository_summary": "PyXDG contains implementations of freedesktop.org standards in python.", "ochrona_severity_score": 3.3, "repo_url": "http://freedesktop.org/wiki/Software/pyxdg", "latest_version": "0.26", "cwe_id": "CWE-59", "language": "python", "publish_date": "2014-01-28T00:55Z", "references": ["http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736247", "http://www.openwall.com/lists/oss-security/2014/01/21/3", "http://www.openwall.com/lists/oss-security/2014/01/21/4", "http://www.securityfocus.com/bid/65042", "https://exchange.xforce.ibmcloud.com/vulnerabilities/90618"], "owner": "python", "affected_versions": [{"operator": "=", "version_value": "0.25"}], "description": "Race condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called."}