{"name": "tensorflow-gpu", "cve_id": "CVE-2020-15202", "publish_date": "2020-09-25T19:15Z", "cwe_id": "CWE-754", "owner": "Google Inc.", "affected_versions": [{"version_value": "1.15.4", "operator": "<"}, {"version_value": "2.0.0", "operator": "="}, {"version_value": "2.0.1", "operator": "="}, {"version_value": "2.0.2", "operator": "="}, {"version_value": "2.1.0", "operator": "="}, {"version_value": "2.1.1", "operator": "="}, {"version_value": "2.2.0", "operator": "="}, {"version_value": "2.3.0", "operator": "="}], "references": ["https://nvd.nist.gov/vuln/detail/CVE-2020-15202", "https://github.com/tensorflow/tensorflow/commit/ca8c013b5e97b1373b3bb1c97ea655e69f31a575", "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-h6fg-mjxg-hqq4", "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00065.html", "https://github.com/advisories/GHSA-h6fg-mjxg-hqq4", "https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1", "https://github.com/tensorflow/tensorflow/commit/27b417360cbd671ef55915e4bb6bb06af8b8a832"], "description": "From NVD:\nIn Tensorflow before versions 1.15.4, 2.0.3, 2.1.2, 2.2.1 and 2.3.1, the `Shard` API in TensorFlow expects the last argument to be a function taking two `int64` (i.e., `long long`) arguments. However, there are several places in TensorFlow where a lambda taking `int` or `int32` arguments is being used. In these cases, if the amount of work to be parallelized is large enough, integer truncation occurs. Depending on how the two arguments of the lambda are used, this can result in segfaults, read/write outside of heap allocated arrays, stack overflows, or data corruption. The issue is patched in commits 27b417360cbd671ef55915e4bb6bb06af8b8a832 and ca8c013b5e97b1373b3bb1c97ea655e69f31a575, and is released in TensorFlow versions 1.15.4, 2.0.3, 2.1.2, 2.2.1, or 2.3.1.\nFrom Github:\n### Impact\nThe `Shard` API in TensorFlow expects the last argument to be a function taking two `int64` (i.e., `long long`) arguments:\nhttps://github.com/tensorflow/tensorflow/blob/0e68f4d3295eb0281a517c3662f6698992b7b2cf/tensorflow/core/util/work_sharder.h#L59-L60\n\nHowever, there are several places in TensorFlow where a lambda taking `int` or `int32` arguments is being used:\nhttps://github.com/tensorflow/tensorflow/blob/0e68f4d3295eb0281a517c3662f6698992b7b2cf/tensorflow/core/kernels/random_op.cc#L204-L205\nhttps://github.com/tensorflow/tensorflow/blob/0e68f4d3295eb0281a517c3662f6698992b7b2cf/tensorflow/core/kernels/random_op.cc#L317-L318\n\nIn these cases, if the amount of work to be parallelized is large enough, integer truncation occurs. Depending on how the two arguments of the lambda are used, this can result in segfaults, read/write outside of heap allocated arrays, stack overflows, or data corruption.\n\n### Patches\nWe have patched the issue in 27b417360cbd671ef55915e4bb6bb06af8b8a832 and ca8c013b5e97b1373b3bb1c97ea655e69f31a575. We will release patch releases for all versions between 1.15 and 2.3.\n\nWe recommend users to upgrade to TensorFlow 1.15.4, 2.0.3, 2.1.2, 2.2.1, or 2.3.1.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by members of the Aivul Team from Qihoo 360.", "latest_version": "2.3.1", "language": "python", "license": "Apache-2.0", "repository_summary": "TensorFlow is an open source machine learning framework for everyone.", "repo_url": "https://github.com/tensorflow/tensorflow", "impact": {"cvss2_score": 6.8, "cvss2_severity": "MEDIUM", "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:H", "av": "NETWORK", "ac": "HIGH", "pr": "NONE", "c": "HIGH", "i": "HIGH", "a": "HIGH", "impact_score": 6.0, "exploitability_score": 2.2, "cvss3_score": 9.0, "cvss3_severity": "CRITICAL", "ui": "NONE", "s": "CHANGED"}, "ochrona_severity_score": 9.0}