{"name": "tensorflow-cpu", "cve_id": "CVE-2020-15196", "publish_date": "2020-09-25T19:15Z", "cwe_id": "CWE-119", "owner": "Google Inc.", "affected_versions": [{"version_value": "2.3.0", "operator": "="}], "references": ["https://nvd.nist.gov/vuln/detail/CVE-2020-15196", "https://github.com/advisories/GHSA-pg59-2f92-5cph", "https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1", "https://github.com/tensorflow/tensorflow/commit/3cbb917b4714766030b28eba9fb41bb97ce9ee02", "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-pg59-2f92-5cph"], "description": "From NVD:\nIn Tensorflow version 2.3.0, the `SparseCountSparseOutput` and `RaggedCountSparseOutput` implementations don't validate that the `weights` tensor has the same shape as the data. The check exists for `DenseCountSparseOutput`, where both tensors are fully specified. In the sparse and ragged count weights are still accessed in parallel with the data. But, since there is no validation, a user passing fewer weights than the values for the tensors can generate a read from outside the bounds of the heap buffer allocated for the weights. The issue is patched in commit 3cbb917b4714766030b28eba9fb41bb97ce9ee02 and is released in TensorFlow version 2.3.1.\nFrom Github:\n### Impact\nThe `SparseCountSparseOutput` and `RaggedCountSparseOutput` implementations don't validate that the `weights` tensor has the same shape as the data. The check exists for `DenseCountSparseOutput`, where both tensors are fully specified:\nhttps://github.com/tensorflow/tensorflow/blob/0e68f4d3295eb0281a517c3662f6698992b7b2cf/tensorflow/core/kernels/count_ops.cc#L110-L117\n\nIn the sparse and ragged count weights are still accessed in parallel with the data:\nhttps://github.com/tensorflow/tensorflow/blob/0e68f4d3295eb0281a517c3662f6698992b7b2cf/tensorflow/core/kernels/count_ops.cc#L199-L201\n\nBut, since there is no validation, a user passing fewer weights than the values for the tensors can generate a read from outside the bounds of the heap buffer allocated for the weights.\n\n### Patches\nWe have patched the issue in 3cbb917b4714766030b28eba9fb41bb97ce9ee02 and will release a patch release.\n\nWe recommend users to upgrade to TensorFlow 2.3.1.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability is a variant of [GHSA-p5f8-gfw5-33w4](https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p5f8-gfw5-33w4)", "latest_version": "2.3.1", "language": "python", "license": "Apache-2.0", "repository_summary": "TensorFlow is an open source machine learning framework for everyone.", "repo_url": "https://github.com/tensorflow/tensorflow", "impact": {"cvss2_score": 6.5, "cvss2_severity": "MEDIUM", "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:H", "av": "NETWORK", "ac": "LOW", "pr": "LOW", "c": "HIGH", "i": "HIGH", "a": "HIGH", "impact_score": 6.0, "exploitability_score": 3.1, "cvss3_score": 9.9, "cvss3_severity": "CRITICAL", "ui": "NONE", "s": "CHANGED"}, "ochrona_severity_score": 9.9}