{"name": "tryton", "cve_id": "CVE-2018-19443", "publish_date": "2018-11-22T19:29Z", "cwe_id": "CWE-384", "owner": "Tryton", "affected_versions": [{"version_value": "5.0.0", "operator": "="}], "references": ["https://nvd.nist.gov/vuln/detail/CVE-2018-19443", "https://bugs.tryton.org/issue7792", "https://discuss.tryton.org/t/security-release-for-issue7792/830", "https://github.com/advisories/GHSA-32w7-9whp-cjp9"], "description": "From NVD:\nThe client in Tryton 5.x before 5.0.1 tries to make a connection to the bus in cleartext instead of encrypted under certain circumstances in bus.py and jsonrpc.py. This connection attempt fails, but it contains in the header the current session of the user. This session could then be stolen by a man-in-the-middle.\nFrom Github:\nThe client in Tryton 5.x before 5.0.1 tries to make a connection to the bus in cleartext instead of encrypted under certain circumstances in bus.py and jsonrpc.py. This connection attempt fails, but it contains in the header the current session of the user. This session could then be stolen by a man-in-the-middle.", "latest_version": "5.8.0", "language": "python", "license": "GPL-3.0-only", "repository_summary": "Tryton desktop client", "repo_url": "https://hg.tryton.org/tryton", "impact": {"cvss2_score": 4.3, "cvss2_severity": "MEDIUM", "vector_string": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N", "av": "NETWORK", "ac": "HIGH", "pr": "NONE", "c": "HIGH", "i": "NONE", "a": "NONE", "impact_score": 3.6, "exploitability_score": 2.2, "cvss3_score": 5.9, "cvss3_severity": "MEDIUM", "ui": "NONE", "s": "UNCHANGED"}, "ochrona_severity_score": 5.9}